### ISSUE TITLE
How to get instance of servers down

### ISSUE THREAD

**Issue by j0k3r2k17** [inCaller/prometheus_bot#33]
I have encountered some trouble is when alert via telegram is only like below:
Status: FIRING 🔥
Active Alert List:
  Alert: 
  Current value:Severity: critical
  Active from:
How can I get the server down?
Thanks u so much !!

**Comment by hryamzik** [comment]
I would start debugging this from Prometheus and Alertmanager UI. Most likely something is wrong with your rules. It could also make sense to get API call from alertmanager to prometheus_bot, it's in json format and easy to read and verify.

**Comment by j0k3r2k17** [comment]
Thanks bro @hryamzik ,I would like to ask more , Can telegram bots be add from CHAT GROUP ID?

**Comment by hryamzik** [comment]
Do you mean reporting to a chat group? Yes it can.

**Comment by j0k3r2k17** [comment]
@hryamzik because , i add a ID group from telegram but log return " Error sending message: Bad Request: chat not found"

**Comment by hryamzik** [comment]
That should mean that bot is not in this chat group or you have an error in chat group ID, I guess you may have missed `-` in it – chat group IDs are negative.

**Comment by j0k3r2k17** [comment]
@hryamzik  Hello bro , 
Can I ask a question as to why when sending a message about a telegram, the message is identical, there is a way to send a message but all the servers down . 
```
#route default
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 7s
  receiver: default
  routes:
#  - match:
#      severity: "critical"
#    receiver: telegram
  - match:
      severity: "critical"
    receiver: default
#  - match:
#      severity: "warning"
#    receiver: thiennt
inhibit_rules:
- source_match:
    severity: 'warning'
#  target_match:
#    severity: 'warning'
# Apply inhibition if the alertname is the same.
  equal: ['alertname']
receivers:
- name: 'default'
  webhook_configs:
  - send_resolved: True
    url: http://127.0.0.1:9087/alert/371135891
``` 
file config alermanager
