### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by yctn** [inCaller/prometheus_bot#42]
So i did a git clone go get and go build and i got the executable. but when i run the executable it just says 2019/02/03 16:08:24 Not Found. what could i be doing wrong, i have setup the config.yaml as described in urreadm.e

**Comment by shipilovds** [comment]
Check if you have correct 'telegram_token' field in your config.yml

**Comment by andrewm41** [comment]
Confirm that with config.yaml
```yaml
telegram_token: "XXX"
split_msg_byte: 4000
send_only: true
```
I get
`2021/06/02 12:09:04 Not Found`
too
